### ISSUE TITLE
Review of full Natagora dataset

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/natagora-alien-occurrences#12]
I reviewed the whole Natagora dataset, below are my remarks. Could you please tick off the boxes when the changes are integrated and send me a new export afterwards?

- [x] type  
- [x] language: should be `en` (now `e`)
- [x] license
- [x] rightsHolder
- [x] accessRights
- [x] references
- [ ] datasetID: to be completed after publication on GBIF
- [x] institutionCode
- [x] datasetName: remove `animal` from title, dataset is applicable to animals, plants and fungi
- [x] basisOfRecord
- [x] informationWithheld
- [x] dataGeneralizations: see #11 
- [x] occurrenceID
- [x] individualCount
- [x] sex
- [x] lifeStage
- [x] behavior: `collected` should be `NA`, see #8 
- [x] occurrenceRemarks: `collected` should be `NA`, see #8 
- [x] samplingProtocol: `collected` should be `specimen collected`, see #8
- [x] dynamicProperties
- [x] reproductiveCondition
- [x] identificationRemarks
- [x] eventDate
- [x] continent
- [x] countryCode: should be `BE` (now `B`)
- [x] stateProvince
- [x] municipality
- [x] decimalLatitude
- [x] decimalLongitude
- [x] geodeticDatum
- [x] coordinateUncertaintyInMeters: for 2745 records the uncertainty is 2828, correct? see #11 
- [x] georeferenceRemarks: coordinates are centroid of used grid square (2745), correct? see #11
- [x] identificationRemarks
- [x] taxonID
- [x] scientificName
- [x] kingdom
- [x] taxonRank
- [x] nomenclaturalCode: Should be `ICZN` for Animalia and `ICN` for plants and fungi

**Comment by peterdesmet** [comment]
We allowed “multispecies” as taxonRank for waarnemingen.be, since speciesAggregate has a slightly different definition.

**Comment by LouisNatagora** [comment]
Thank you, Lean, for this exhaustive listing. 
What do you mean with "informationWithheld"? You forgot to add any comment.

**Comment by LienReyserhove** [comment]
Sorry, my mistake, the field `informationWithheld` is OK!

**Comment by LienReyserhove** [comment]
Thanks a lot for the integrated changes!
Dataset looks great now, ready for publication after the metadata is reviewed (I will let you know asap).

Just to be sure: the dataset can be published with **generalized records** (see https://github.com/trias-project/natagora-alien-occurrences/issues/11#issuecomment-505753643).

**Comment by LouisNatagora** [comment]
The correct dataset has been uploaded to the IPT and test datasets have been removed.
